name: Weekly Data Fetch

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: {}

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      - name: Create .env file
        run: |
          touch .env
          echo GOOGLE_REVIEWS_API=${{ secrets.GOOGLE_REVIEWS_API }} >> .env
          cat .env

      - name: Run data fetching script
        run: node src/lib/reviews.js
